### ISSUE TITLE
Murmur hash gives different hash values for same input value

### ISSUE THREAD

**Issue by arthurvb** [saguiitay/CardinalityEstimation#12]
When using cardinalityestimation with "long" as input object, murmur seems to give different hashes for the same values (at least sometimes, 64 bit machine). Setting the hash function to fnv1a resolves the issue.

I will probably look into this a bit more, but since this was _very_ hard to debug, I thought I'll warn other users :-)

Regards,

Arthur

**Comment by melnikov77** [comment]
Maybe this happens because the Murmur3 is not thread safe i.e.  if you call it from different threads you could have a wrong hash.

**Comment by oronnavon** [comment]
Thanks Sergey for the fix!

**Comment by arthurvb** [comment]
Thanks, will check the fix, however I see the same when I use the cardinality estimation in a single thread. I think it is might because I add "long" numbers. I check adding 10000000 random numbers between 10000000 and 10000100, so only 100 different numbers. And when I compare with a hashset the hashset actually contains 100 numbers and the estimator estimates more (which it is not expected since we have a directcount). The strange thing is that it only occurs sometimes although I initiate my random number generator with a fixed seed and the code is not multithreaded (unless the cardinality estimator adds multi threading).

**Comment by arthurvb** [comment]
Ok, my test  was wrong since I used testmethods for both the multithreaded and singlethreaded scenario. And, since the test-methods run in parallel and the Murmur3-hash is static, even the singlethreaded testmethod actually tested the multithreaded scenario.. :-S.
Running a much larger test on the single-threaded scenario confirmed the observation that the issue was the thread-safety.
Thanks for fixing!

Arthur

**Comment by melnikov77** [comment]
Hi Oron,

Are you planing to publish these changes to nuget?

Thanks,
Sergey

**Comment by oronnavon** [comment]
Hi Sergey,Thanks for the reminder :) Published as 1.2.1.
Thanks,Oron

Date: Fri, 19 Aug 2016 15:32:49 -0700
