### ISSUE TITLE
CardinalityEstimation is not supported on .net core

### ISSUE THREAD

**Issue by sxmichael** [saguiitay/CardinalityEstimation#17]
Any reason for that?
```
Restoring packages for ...
Package CardinalityEstimation 1.5.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package CardinalityEstimation 1.5.0 supports: net45 (.NETFramework,Version=v4.5)
Package murmurhash 1.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package murmurhash 1.0.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes.
Time Elapsed: 00:00:01.6802616
========== Finished ==========

```

**Comment by oronnavon** [comment]
Probably no serious reason. I have zero experience with .NET Core but I'd wager it's just a matter of compiling our dependency murmurhash with .NET Core and publishing to NuGet. I'll contact the owner @darrenkopp and ask.

**Comment by darrenkopp** [comment]
hey @sxmichael i just pushed a new version of the package which targets .net standard 1.4. let me know if that doesn't work for you and i can look further into targeting something lower.

**Comment by sxmichael** [comment]
@darrenkopp thanks a lot! Now murmurhash nuget package is .net core compatible.

@oronnavon I tried to create a project for .net core for CardinalityEstimation and compile manually. After murmurhash package was updated, one thing which was missing is System.Runtime.Serialization.Primitives nuget package (in .net core System.Runtime.Serialization was moved  to separate lib: https://github.com/dotnet/docs/issues/319).
After this only two errors left: 
```
The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'NonSerializedAttribute' could not be found (are you missing a using directive or an assembly reference?)
```

Both attributes are used on CardinalityEstimator class. It seems like those are needed for BinaryFormatter, which is not supported in .net core, at least till version 2.0: https://github.com/dotnet/coreclr/issues/1203

**Comment by oronnavon** [comment]
@sxmichael So it seems to me we can afford to skip .NET Core 1.1 support. Would appreciate if you would give it a shot adding .NET Core 2.0 support.

**Comment by saguiitay** [comment]
@sxmichael I've just merged https://github.com/Microsoft/CardinalityEstimation/pull/22 which should add support for .Net Core 2.0

**Comment by saguiitay** [comment]
Version 1.7 is now publicly available in NuGet.Org: https://www.nuget.org/packages/CardinalityEstimation/
