### ISSUE TITLE
Publish signed version of .NET Standard-compatible library

### ISSUE THREAD

**Issue by swannman** [saguiitay/CardinalityEstimation#24]
It looks like there are two NuGets available:
- **CardinalityEstimation**: .NET Standard, not strong-name signed
- **CardinalityEstimation.Signed**: .NET Framework, strong-name signed

We'd like to use the CardinalityEstimation library in a .NET Core project that requires strong-name signed assemblies. Would you be willing to update the CardinalityEstimation.Signed nuget to the .NET Standard version?

**Comment by saguiitay** [comment]
@oronnavon can you please add me as an owner of the CardinalityEstimation.Signed Nuget package, so that I can update it?

**Comment by oronnavon** [comment]
Added, you should get a confirmation notice
