### ISSUE TITLE
High error for sequential sets - consider MurmurHash instead of FNV

### ISSUE THREAD

**Issue by oronnavon** [saguiitay/CardinalityEstimation#8]
The current implementation shows much higher error rates in the edge case where IDs of counted objects are sequential (e.g. 1, 2, 3... when counting integers).  It appears that MurmurHash has better avalanche characteristics than the FNV hash, playing around some seems to confirm this.

There is a good C# implementation of MurmurHash with a suitable license here https://github.com/darrenkopp/murmurhash-net . It needs some minor modification but will work well for CardinalityEstimation.

**Comment by rk2012** [comment]
I am also seeing very high error for sequences. @oronnavon , do you have the MurmuHash changes in some fork ? Would like to try it out.

**Comment by oronnavon** [comment]
Sure, I'll clean it up a bit this week and push

**Comment by oronnavon** [comment]
Pushed, feel free to comment. Some UTs are still not implemented, I'll complete them and merge to master probably next week.
https://github.com/Microsoft/CardinalityEstimation/tree/murmur3
Pull request: https://github.com/Microsoft/CardinalityEstimation/pull/9

**Comment by oronnavon** [comment]
Resolved with merge of Murmur3 branch
